---
version: '2'

services:
  db:
    image: mysql
    container_name: database
    volumes:
      - vol_sitedb:/var/lib/mysql

    env_file:
      - ./database.env

  web:
    build: .
    image: jb/drupalbrisb:0.1
    container_name: drubri03
    ports:
      - "82:80"
    volumes:
      - vol_sitefiles:/var/www/drupal_site/sites/default/files
    links:
      - db:database

    environment:
      - DB_DRIVER=mysql
      - MYSQL_HOST=database

    env_file:
      - ./database.env

volumes:
  vol_sitefiles:
  vol_sitedb:
